### ISSUE TITLE
Onboarding to DYDX using this client library using just and Ethereum Address

### ISSUE THREAD

**Issue by 0x4a5e1e4baab** [go-numb/go-dydx#7]
As per title is is possible to onboard just using a Ethereum address,

i see much code that refers to derive a stark key from a Eth address but i dont see this code called anywhere 

https://github.com/go-numb/go-dydx/search?q=DeriveStarkKey

**Comment by 0x4a5e1e4baab** [comment]
algo get errors

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1002c2ad7]

goroutine 1 [running]:
github.com/go-numb/go-dydx/helpers.(*SignOnboardingAction).Sign(0xc0001a47b0, {0xc0003a0870, 0x2a}, 0xc0003a2c90)
        /Users/0x4a5e1e4baab/go/pkg/mod/github.com/go-numb/go-dydx@v0.0.0-20230206162946-5808a89eacd0/helpers/calc.go:49 +0x357
github.com/go-numb/go-dydx/onboard.(*OnBoarding).DeriveStarkKey(0xc0002e8c40, {0xc0003a0870, 0x2a})
        /Users/0x4a5e1e4baab/go/pkg/mod/github.com/go-numb/go-dydx@v0.0.0-20230206162946-5808a89eacd0/onboard/onboarding.go:66 +0xbb
github.com/go-numb/go-dydx.New({0x0, {0x100481dc8, 0x19}, {0xc0003a0870, 0x2a}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
        /Users/0x4a5e1e4baab/go/pkg/mod/github.com/go-numb/go-dydx@v0.0.0-20230206162946-5808a89eacd0/client.go:91 +0x6d5
```
